version: 2.1

jobs:
  say-hello:
    macos:
      xcode: 15.0.0
      
    steps:
      - run: brew install xcodesorg/made/xcodes && xcodes runtimes && curl 'https://api.ipify.org?format=json' && system_profiler SPSoftwareDataType SPHardwareDataType
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
